CREATE DATABASE Pessoas;

USE Pessoas;

CREATE TABLE Pessoas
(
	idPessoa INT PRIMARY KEY IDENTITY
	,Nome VARCHAR(200) NOT NULL
	,RG VARCHAR(200) NOT NULL
);

CREATE TABLE Telefones
(
	idTelefone INT PRIMARY KEY IDENTITY
	,idPessoa INT FOREIGN KEY REFERENCES Pessoas(idPessoa)
	,Numero INT 
	,DDD INT
);
CREATE TABLE Emails
(
	idEmail INT PRIMARY KEY IDENTITY
	,idPessoa INT FOREIGN KEY REFERENCES Pessoas(idPessoa)
	,Email VARCHAR(200) NOT NULL
);
CREATE TABLE CNHs
(
	idCnh INT PRIMARY KEY IDENTITY
	,CNH VARCHAR(200) NOT NULL
	,Categoria VARCHAR(200) NOT NULL
);